---
apiVersion: v2
name: sausage-store
description: Sausage Store Helm Chart
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: backend
    version: 0.1.0
    repository: file://charts/backend
  - name: backend-report
    version: 0.1.0
    repository: file://charts/backend-report
  - name: frontend
    version: 0.1.0
    repository: file://charts/frontend
  - name: infra
    version: 0.1.0
    repository: file://charts/infra