apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
spec:
  replicas: {{ .Values.backend-report.replicas }}
  revisionHistoryLimit: {{ .Values.backend-report.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.backend-report.strategy.type }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sausage-backend-report
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sausage-backend-report
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app.kubernetes.io/component: backend-report
        app.kubernetes.io/part-of: sausage-store
    spec:
      containers:
        - name: backend-report
          image: "{{ .Values.backend-report.image }}"
          imagePullPolicy: {{ .Values.backend-report.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend-report.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.backend-report.resources | nindent 12 }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-report-config
                  key: PORT
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: backend-report-secret
                  key: DB 