{{- if .Values.backend-report.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-report
  labels:
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-report
  minReplicas: {{ .Values.backend-report.hpa.minReplicas }}
  maxReplicas: {{ .Values.backend-report.hpa.maxReplicas }}
  metrics:
    {{- toYaml .Values.backend-report.hpa.metrics | nindent 4 }}
{{- end }} 