name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  NEXUS_HELM_REPO: https://nexus.cloud-services-engineer.education-services.ru/repository/helm-sausage-store
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/sausage-store/sausage-backend:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/sausage-store/sausage-frontend:latest

      - name: Build and push Backend-report
        uses: docker/build-push-action@v4
        with:
          context: ./backend-report
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/sausage-store/sausage-backend-report:latest

  package-and-push-helm:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Package Helm chart
        run: |
          cd sausage-store-chart
          helm package .

      - name: Push Helm chart to Nexus
        run: |
          curl -u ${{ env.NEXUS_HELM_REPO_USER }}:${{ env.NEXUS_HELM_REPO_PASSWORD }} \
            -F "helm.asset=@sausage-store-chart/sausage-store-chart-0.1.0.tgz" \
            ${{ env.NEXUS_HELM_REPO }}

  deploy-to-kubernetes:
    needs: package-and-push-helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Add Nexus Helm repository
        run: |
          helm repo add nexus ${{ env.NEXUS_HELM_REPO }} \
            --username ${{ env.NEXUS_HELM_REPO_USER }} \
            --password ${{ env.NEXUS_HELM_REPO_PASSWORD }}
          helm repo update

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install sausage-store nexus/sausage-store-chart \
            --namespace ${{ secrets.KUBERNETES_NAMESPACE }} \
            --set frontend.fqdn=front-${{ secrets.STUDENT_NAME }}.2sem.students-projects.ru \
            --set backend.image=${{ env.DOCKERHUB_USERNAME }}/sausage-store/sausage-backend:latest \
            --set frontend.image=${{ env.DOCKERHUB_USERNAME }}/sausage-store/sausage-frontend:latest \
            --set backend-report.image=${{ env.DOCKERHUB_USERNAME }}/sausage-store/sausage-backend-report:latest 